# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli
[print_schema]
file = "../../src/model/diesel/fortune/fortune_schema.rs"
with_docs = false

# This will cause only the users and posts tables to be output
filter = { only_tables = [
    "bill_book_template_contents",
    "bill_book_contents",
    "bill_record",
    "bill_book_template",
    "bill_book",
    "user_action_log",
    "role",
    "user_role",
    "permission",
    "role_permission",
    "bill_book_role"
] }

